### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by wendingzhulu** [airbnb/reair#66]
I start the ReAir jar for replicate source warehouse to dest warehouse. But i found the exception as follow, and I don't know why
`17/05/23 17:05:33 INFO mapreduce.Job: The url to track the job: http://cdh.master.linesum:8088/proxy/application_1495527145657_0006/
17/05/23 17:05:33 INFO mapreduce.Job: Running job: job_1495527145657_0006
17/05/23 17:05:38 INFO mapreduce.Job: Job job_1495527145657_0006 running in uber mode : false
17/05/23 17:05:38 INFO mapreduce.Job:  map 0% reduce 0%
17/05/23 17:05:41 INFO mapreduce.Job: Task Id : attempt_1495527145657_0006_m_000001_0, Status : FAILED
Error: java.util.NoSuchElementException
        at java.util.AbstractList$Itr.next(AbstractList.java:364)
        at com.google.common.collect.Iterators.any(Iterators.java:684)
        at com.google.common.collect.Iterables.any(Iterables.java:620)
        at com.airbnb.reair.batch.hive.TableCompareWorker.processTable(TableCompareWorker.java:123)
        at com.airbnb.reair.batch.hive.MetastoreReplicationJob$Stage1ProcessTableMapper.map(MetastoreReplicationJob.java:570)
        at com.airbnb.reair.batch.hive.MetastoreReplicationJob$Stage1ProcessTableMapper.map(MetastoreReplicationJob.java:556)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
`

**Comment by plypaul** [comment]
Something to do with the blacklist? Please re-open and tag me if this is still an issue.
